apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: 879772956301.dkr.ecr.ca-central-1.amazonaws.com/user22-payment:latest
          ports:
            - containerPort: 8080
